import '../models/seed_image.dart';

const List<SeedImage> seedImages = [
  SeedImage(id: 'zinnia', assetPath: 'assets/images/seeds/Zinnia.png'),
  SeedImage(id: 'hollyhock', assetPath: 'assets/images/seeds/Hollyhock.png'),
  SeedImage(id: 'agrostemma', assetPath: 'assets/images/seeds/Agrostemma.png'),
  SeedImage(
    id: 'bells of ireland',
    assetPath: 'assets/images/seeds/Bells of Ireland.png',
  ),
  SeedImage(id: 'calendula', assetPath: 'assets/images/seeds/Calendula.png'),
  SeedImage(id: 'celosia 1', assetPath: 'assets/images/seeds/Celosia 1.png'),
  SeedImage(id: 'centaurea', assetPath: 'assets/images/seeds/Centauria.png'),
  SeedImage(id: 'cosmos', assetPath: 'assets/images/seeds/Cosmos.png'),
  SeedImage(id: 'didiscus', assetPath: 'assets/images/seeds/Didiscus.png'),
  SeedImage(id: 'echinacea', assetPath: 'assets/images/seeds/Echinacea.png'),
  SeedImage(id: 'gomphrena', assetPath: 'assets/images/seeds/Gomphrena.png'),
  SeedImage(id: 'marigold', assetPath: 'assets/images/seeds/Marigold.png'),
  SeedImage(id: 'tomatoroma', assetPath: 'assets/images/seeds/Roma Tomato.png'),
  SeedImage(id: 'rubeckia', assetPath: 'assets/images/seeds/Rubeckia.png'),
  SeedImage(id: 'scabiosa', assetPath: 'assets/images/seeds/Scabiosa.png'),
  SeedImage(
    id: 'Shastadaisy',
    assetPath: 'assets/images/seeds/Shasta daisy.png',
  ),
  SeedImage(id: 'snapdragon', assetPath: 'assets/images/seeds/Snapdragon.png'),
  SeedImage(id: 'sunflower', assetPath: 'assets/images/seeds/Sunflower.png'),
  SeedImage(
    id: 'sweetwilliam',
    assetPath: 'assets/images/seeds/Sweet William.png',
  ),
  SeedImage(id: 'tomato', assetPath: 'assets/images/seeds/Tomato.png'),
  SeedImage(id: 'zinnia', assetPath: 'assets/images/seeds/Zinnia.png'),
  SeedImage(id: 'aubergine', assetPath: 'assets/images/seeds/Aubergine.png'),
  SeedImage(id: 'eggplant', assetPath: 'assets/images/seeds/Aubergine.png'),
  SeedImage(id: 'cucumber', assetPath: 'assets/images/seeds/Cucumber.png'),
  SeedImage(id: 'lettuce', assetPath: 'assets/images/seeds/Lettuce.png'),
  SeedImage(id: 'pumpkin', assetPath: 'assets/images/seeds/Pumpkin.png'),
  SeedImage(id: 'watermelon', assetPath: 'assets/images/seeds/Melon.png'),
  SeedImage(id: 'melon', assetPath: 'assets/images/seeds/Melon.png'),
  SeedImage(id: 'stocks', assetPath: 'assets/images/seeds/Stocks.png'),
  SeedImage(id: 'foxglove', assetPath: 'assets/images/seeds/Foxglove.png'),
  SeedImage(id: 'poppy', assetPath: 'assets/images/seeds/Poppy.png'),
  SeedImage(id: 'carrot', assetPath: 'assets/images/seeds/Carrot.png'),
  SeedImage(id: 'spinach', assetPath: 'assets/images/seeds/Spinach.png'),
  SeedImage(id: 'dahlia', assetPath: 'assets/images/seeds/Dahlia.png'),
  SeedImage(id: 'onion', assetPath: 'assets/images/seeds/Onion.png'),
  SeedImage(id: 'statice', assetPath: 'assets/images/seeds/Statice.png'),
  SeedImage(id: 'primula', assetPath: 'assets/images/seeds/Primula.png'),
  SeedImage(id: 'cabbage', assetPath: 'assets/images/seeds/Cabbage.png'),
];
